# Follow some folks

Let's start by downloading the Twitter app on your phone, or visiting the [desktop site](https://twitter.com/){target="_blank"}. Create an account and you're good to go.

When your first start, you'll be prompted to follow some popular accounts. Go ahead and select a few. Don't worry about which you select, we'll show you how to unfollow accounts later. For now, just pick a few and continue.

The key to making Twitter work for you is to follow accounts that you find interesting. Accounts can be owned either by individuals or admistered by companies. 

Twitter will often recommend accounts for you to follow. 
Some may be relevant, so go ahead and follow them. 
Over time, you'll find that you follow more and more accounts. 

## Following people and organisations

You can find people to follow by searching for their Twitter handle. 
This is a unique identifier associated with each account. 

For example, Allison Horst's tag is "@allison_horst". 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Comparing scenarios &amp; connecting sample differences to p-values to evidence for population differences. <a href="https://t.co/9qrHVoDS76">pic.twitter.com/9qrHVoDS76</a></p>&mdash; Allison Horst (<mark>@allison_horst</mark>) <a href="https://twitter.com/allison_horst/status/1216411299875192837?ref_src=twsrc%5Etfw">January 12, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

Tags are the basis for interacting with other accounts on Twitter. When you want to mention someone in a tweet, a tag is how you'll do it. We'll do some practice tweeting soon!

We've listed a few accounts for you to follow and get some practice at the same time. 
These are some prominent members of the R community and they post good stuff. 
Go ahead and search for these accounts and follow them. Let's walk you through the first one. 

1. Select the search bar (the magnifying glass icon ðŸ” ) 
1. Search for Hadley Wickham by typing **[\@hadleywickham](https://twitter.com/hadleywickham){target="_blank"}** in the search bar. 
1. Hadley's profile will come up. 
1. Select it. 
1. Select the **follow** button.


    
Well done! 
You've followed your first person :).

Now go ahead and follow a few other prominent R-people:

* Mara Averick: **[\@dataandme](https://twitter.com/dataandme){target="_blank"}**
* Caitlin Hudon: **[\@beeonaposy](https://twitter.com/beeonaposy){target="_blank"}**
* Thomas Mock: **[\@thomas_mock](https://twitter.com/thomas_mock){target="_blank"}**
* Gina Reynolds: **[\@EvaMaeRey](https://twitter.com/EvaMaeRey){target="_blank"}**
* Jenny Bryan: **[\@JennyBryan](https://twitter.com/JennyBryan){target="_blank"}**


There are also great organisational accounts:

* R4DS online learning community: **[\@R4DScommunity](https://twitter.com/R4DScommunity){target="_blank"}**
* R-Ladies Global: **[\@RLadiesGlobal](https://twitter.com/RLadiesGlobal){target="_blank"}**


You may start remembering people by their Twitter handle rather than their actual name!

Oh yes, you can also go ahead and follow Oscar and Veerle if you'd like to :). 

* Oscar Baruffa: **[\@oscarbaruffa](https://twitter.com/OscarBaruffa){target="_blank"}**
* Veerle van Son: **[\@veerlevanson](https://twitter.com/veerlevanson){target="_blank"}** 


Now that you're following people your feed will be populated by what they *post*, what they *like* and *re-tweet*.
We'll dive a little deeper into how the feed works a little later.  

But first: 

### A note on your own follower count


This can't be stressed enough.

> Ignore your own follower count. 

It's a great boost to ego as your follower number grows, but the benefit you get comes from following other accounts, not who follows you. _ðŸ¤ž hopes that Hadley followsðŸ¤ž _ 

You may get some followers yourself but that has no bearing on how much value you'll get from using Twitter.

## How to unfollow people

When you first signed up to Twitter, you were prompted to *follow* some popular accounts and you can now practice *unfollowing* on these.

First let's go back to those accounts you followed earlier. Your accounts will be different from these but the steps remain the same. 

1. Select your own profile photo on the top left of the screen, this opens your menu. 
1. Tap on the "6 Following" number, your number might be different to this.
1. You can unfollow accounts by tapping on the "Following" button. 

You can also *unfollow* directly from your feed like this.

1. Look at any tweet from the account you wish to unfollow and tap the little drop-down arrow to the right of the account name. 
1. Select Unfollow. 


Well done! You're already getting the hang of this. Let's have a closer look at how your Twitter feed works. 

