# #Hashtags, what are they good for?

Quite a lot, actually. By now hashtags have found their way across multiple social media platforms. On Twitter, selecting any hashtag you see will take you to a list of tweets that feature that tag. It's a way to quickly see a list of tweets about a specific topic. 

Some important hashtags for your R journey are:


## #RStats
To indicate that a tweet is about an R-related topic, the #rstats hashtag is used. As a hashtag consisting of just one letter (#R) didn't quite cut it, the hashtag that was settled on was [#rstats](https://twitter.com/search?q=%23rstats){target="_blank"}. First used in 2009, it is now probably the most widely used hashtag by the R Twitter community. 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">RT <a href="https://twitter.com/chrisalbon?ref_src=twsrc%5Etfw">@ChrisAlbon</a> <a href="https://twitter.com/drewconway?ref_src=twsrc%5Etfw">@drewconway</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> is the official R statistical language hashtag. <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> (because <a href="https://twitter.com/hashtag/R?src=hash&amp;ref_src=twsrc%5Etfw">#R</a> doesn&#39;t cut it)</p>&mdash; Michael E. Driscoll (@medriscoll) <a href="https://twitter.com/medriscoll/status/1448139141?ref_src=twsrc%5Etfw">April 3, 2009</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">I declare <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> the official R statistical prog lang hashtag, pass it on to friends, family and Stata users</p>&mdash; Drew Conway (@drewconway) <a href="https://twitter.com/drewconway/status/1448027809?ref_src=twsrc%5Etfw">April 3, 2009</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
  
<br/><br/>
  
The [\@rstatstweet](https://twitter.com/rstatstweet) account retweets any tweets that contain the [#rstats](https://twitter.com/search?q=%23rstats&src=typed_query) hashtag. The good thing about this is that your tweet will get more exposure. A possible downside from following the [\@rstatstweet](https://twitter.com/rstatstweet) account is that you might get overwhelmed by the huge amount of tweets that use this hashtag. 


## #TidyTuesday

Every week there is a Tidy Tuesday challenge posted. It's a dataset that everyone makes visualisations about and shares their results (and often source code too!). This is a fun way to improve your own skills by learning how others do things and practicing on interesting datasets. Read more about Tidy Tuesday on their [Github page](https://github.com/rfordatascience/tidytuesday). New [#TidyTuesday](https://twitter.com/search?q=%23TidyTuesday&src=typed_query) data sets are posted on Twitter by [\@thomas_mock](https://twitter.com/thomas_mock), usually on Monday. Search for or click on the [#TidyTuesday](https://twitter.com/search?q=%23TidyTuesday&src=typed_query&f=live) hashtag to see all the visualisations that were posted recently. 

To easily browse older [#TidyTuesday](https://twitter.com/search?q=%23TidyTuesday&src=typed_query&f=live) tweets, you can use the awesome Shiny app created by [\@nealgrantham](https://twitter.com/nsgrantham). It can be found at [tidytuesday.rocks](https://nsgrantham.shinyapps.io/tidytuesdayrocks/), and you can filter tweets by data set or by user. 


<blockquote class="twitter-tweet"><p lang="en" dir="ltr">The <a href="https://twitter.com/R4DScommunity?ref_src=twsrc%5Etfw">@R4DScommunity</a> welcomes you to week 7 of <a href="https://twitter.com/hashtag/TidyTuesday?src=hash&amp;ref_src=twsrc%5Etfw">#TidyTuesday</a>! We&#39;re exploring Hotel Bookings and tidy time-series with {tsibble}!<br><br>📁 <a href="https://t.co/sElb4fcv3u">https://t.co/sElb4fcv3u</a><br>📰 <a href="https://t.co/aaRUiVwpku">https://t.co/aaRUiVwpku</a><a href="https://twitter.com/hashtag/r4ds?src=hash&amp;ref_src=twsrc%5Etfw">#r4ds</a> <a href="https://twitter.com/hashtag/tidyverse?src=hash&amp;ref_src=twsrc%5Etfw">#tidyverse</a> <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a> <a href="https://t.co/QG8QpzCugr">pic.twitter.com/QG8QpzCugr</a></p>&mdash; Tom Mock (@thomas_mock) <a href="https://twitter.com/thomas_mock/status/1226904631390998528?ref_src=twsrc%5Etfw">February 10, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>




## Event hashtags

One of the best aspects of Twitter is following news about events and conferences. Of of the most popular is RStudioConf. The hashtag [#rstudioconf](https://twitter.com/search?q=%23rstudioconf){target="_blank"} becomes really active leading up to and during the event. If you're not attending the conference, following this hashtag gives you an idea of what's going on during the conference. Tweets often contain take-home messages of talks, screenshots, or links to slides. People attending the conference often use Twitter to meet up for coffee, or to get info on sessions that are cancelled.

Other event hashtags:

- #useR + year, eg. #useR2020
- #eRum + year, eg. #eRum2020
- #SatRday

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">can&#39;t believe <a href="https://twitter.com/hashtag/rstudioconf?src=hash&amp;ref_src=twsrc%5Etfw">#rstudioconf</a> talks are already online!! go watch me laugh at my own jokes for 20 minutes (and also learn a bit about repeated reporting) <a href="https://t.co/hfKu1vhNzp">https://t.co/hfKu1vhNzp</a></p>&mdash; Sharla Gelfand (@sharlagelfand) <a href="https://twitter.com/sharlagelfand/status/1225516760247472130?ref_src=twsrc%5Etfw">February 6, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

