# All about bots

There are some accounts that may look a bit odd or behave strangely. These are generally bots. 
We'll introduce some of these to you below. 


## Benign bots
Tweets are related to things like the weather forecasts, or perhaps some mundane activity that somewhere, someone, finds useful.

This bot is tweeting the weather for Utrecht, Netherlands. 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">current weather in Utrecht: few clouds, 9°C<br>70% humidity, wind 10kmh, pressure 1016mb</p>&mdash; Utrecht Weather (@_UtrechtNL) <a href="https://twitter.com/_UtrechtNL/status/1229813120882708481?ref_src=twsrc%5Etfw">February 18, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Funny bots
Tweets are usually humourous or related to some sort of activity like repling to tweets with words replaced by something humorous. In the exampel below, someone's made a program that creates new emoji and automatically posts the results. 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">🥳 partying + 😭 in-tears = <a href="https://t.co/CVTUAysvfM">pic.twitter.com/CVTUAysvfM</a></p>&mdash; Emoji Mashup Bot (@EmojiMashupBot) <a href="https://twitter.com/EmojiMashupBot/status/1152683511863750656?ref_src=twsrc%5Etfw">July 20, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


### Dead accounts
You might find you want to follow your favourite band or some person who hasn't tweeted in ages, or never tweeted. This happens and these accounts are sometimes created to be able to claim the Twitter tag which may have some significance to the owner. Or the owner doesn't use the account anymore, but never bothered to delete it. 


