# What you can get out of Twitter

So, you're an R-programmer. What can you gain from becoming active on Twitter?

First of all, what is Twitter exactly?

## First things first: What is Twitter?

Microblogging website
Follow anyone (unlike Facebook, Twitter is not based on who you know in real life) You follow people based on whether you think their content is interesting

## Why use Twitter as an R-programmer
Friendly community

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Twitter is a fantastic resource for learning new tips and tricks with <a href="https://twitter.com/hashtag/R?src=hash&amp;ref_src=twsrc%5Etfw">#R</a>, especially when it comes to <a href="https://twitter.com/hashtag/dataviz?src=hash&amp;ref_src=twsrc%5Etfw">#dataviz</a>! I love how supportive the <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> community is. 🤓 <a href="https://t.co/9qMwbXkvEQ">https://t.co/9qMwbXkvEQ</a></p>&mdash; Julian Gan (@JCLGan) <a href="https://twitter.com/JCLGan/status/1229486581620367361?ref_src=twsrc%5Etfw">February 17, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

People use Twitter to learn about new job opportunities,
collaborations on scientific projects, keeping up with newly released R-packages, learning about conferences, asking your R-related questions

Lots of people in the R community have blogs, and they will tweet about it if they published a new blog post. 

Not only serious, also lots of programming jokes
Sense of community, especially useful if you're the only one using R in your company or institution. 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Goodnight columns, goodnight rows,<br>Goodnight kind strangers on Stack Overflow,<br>Goodnight factors, goodnight strings,<br>Goodnight overfitted things,<br>Goodnight humans, goodnight bots,<br>Goodnight inconclusive plots.<br>Goodnight R 😴<a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a></p>&mdash; Olga Boichak (@olgarithmic) <a href="https://twitter.com/olgarithmic/status/1057093358374604800?ref_src=twsrc%5Etfw">October 30, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 

Tidy Tuesday (more about this later in the book)

## Making friends on Twitter is a real thing

Maybe it's hard to picture if you haven't used Twitter before, but it's a place where you can actually connect with other people. Sometimes you get to meet the friends you made on Twitter in real life, eg. at a conference. 

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Person at an event: oh hi, I know you from twitter<br>Me: ...sorry remind me?<br>Person: *says his name, full job title, things we talked about*<br>Me: ...er...?<br>Person: my profile picture is a banana?<br>Me: Banana!!! How are you?! So great to meet in real life!</p>&mdash; Robyn Vinter (@RobynVinter) <a href="https://twitter.com/RobynVinter/status/1225839669201469445?ref_src=twsrc%5Etfw">February 7, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 
