# Diving deeper into R and Twitter

Now that you've got the hang of Twitter - here are some more advanced things you can do. 

## Curating the WeAreRLadies account
[\@WeAreRLadies](https://twitter.com/WeAreRLadies){target="_blank"} is a so-called rotating curation Twitter account: each week, a different awesome R-Lady takes over! They take control of the account for one week, and often tweet about how they use R in their job. The account was created by [R-Ladies Global](https://rladies.org/){target="_blank"}.

If you are female or non-binary, you can sign up to tweet from the [\@WeAreRLadies](https://twitter.com/WeAreRLadies){target="_blank"} account for a week! More information and the application form can be [found here](https://docs.google.com/forms/d/e/1FAIpQLSevtboT8TNjz87qe5HZzuBHuY0aNteaZNF5e2xFQXtSeU0c0w/viewform){target="_blank"}.


## Scheduling tweets
Instead of sending your tweet into the world right away, you can schedule it to be sent out at a specific date and time. Maybe your tweet is about a specific event, and you only want your tweet to appear when the event has started. First, write your tweet like you would normally do. To schedule, click the calendar / clock icon and choose date and time. The **Tweet** button is now a **Schedule** button. Click the button and you're done! Under the calendar / clock icon, you can also select the **Scheduled tweets** at the bottom to see a list of tweets you've scheduled but that haven't been sent yet.

Note: This feature hasn't been rolled out to all accounts yet. 


## Analyzing Twitter data with rtweets
Twitter is a great source of data for all sorts of analyses. You can use the excellent [rtweet](https://rtweet.info/index.html){target="_blank"} package to access the data. 


<blockquote class="twitter-tweet"><p lang="en" dir="ltr">😍🤓📖 - Just had the pleasure of reading through some of the <a href="https://twitter.com/hashtag/rtweet?src=hash&amp;ref_src=twsrc%5Etfw">#rtweet</a> documentation, and boy is it great!!<br><br>I feel like <a href="https://twitter.com/kearneymw?ref_src=twsrc%5Etfw">@kearneymw</a> has really set the gold standard for this one. He&#39;s even made the external API dependencies approachable. <br><br>Great work!!! <a href="https://twitter.com/hashtag/rstats?src=hash&amp;ref_src=twsrc%5Etfw">#rstats</a> <a href="https://twitter.com/hashtag/data?src=hash&amp;ref_src=twsrc%5Etfw">#data</a> <a href="https://t.co/NHOUykBylL">pic.twitter.com/NHOUykBylL</a></p>&mdash; Laura Ellis (@LittleMissData) <a href="https://twitter.com/LittleMissData/status/1231946255468814340?ref_src=twsrc%5Etfw">February 24, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


## Sending tweets from inside Rstudio
Using either the [rtweet](https://rtweet.info/index.html){target="_blank"} or tweetRcode packages, you can send tweets directly from Rstudio.



 
 