# Tips for a great experience

We advise you treat Twitter like a garden that needs to be cultivated. That means you need to do a lot of weeding! Be comfortable with unfollowing people - you caN always follow them again if you want to.

Block people easily - there's no need for idiots to fill up your feed :).  
You don't need to listen to everyone's views. This can be your happy place online and you don't need permission to make it so.

## Mute words

Specifying mute words keeps any tweets with those words out of your feed. Mute words come in handy when you want to see someone's R code and cat pics, but not their political tweets. Especially if it's politics of a country you don't live in, and therefore you don't find tweets on the topic very relevant. 

Tweets containing your mute words might still end up in your feed if someone quote tweets it. The mute doesn't pick those up.

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">|￣￣￣￣￣￣ |<br>| MUTE |<br>| EARLY | <br>| AND | <br>| OFTEN |<br>| ＿＿＿＿＿__| <br>(\__/) || <br>(•ㅅ•) || <br>/ 　 づ</p>&mdash; Sharla Gelfand (@sharlagelfand) <a href="https://twitter.com/sharlagelfand/status/1232161684820811776?ref_src=twsrc%5Etfw">February 25, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>


Oscar's current mute list as of 31 January 2020

* Republican

* Dems

* Democrats

* Kavanaugh

* Facebook

* Democrat

* GOP

* Kanye West


This has vastly improved my experience :).

