# Your first tweets
Enough of the tour, let's get you tweeting! 

Select the compose tweet button and start typing - note that Pyou can't edit a tweet once it's posted*. Don't worry, everyone has forgiven spellign msiatkes in tweets long ago :).

Say anythign you want, or if you're stuck for inspiration say "Yay! My first tweet!", or the ever famous, "Hello, world!". 

Now try another tweet, this time tagging people. Say something like "Hey @veerlevanson @oscarb I'm trying this twitter thing out." We'll both get notifications of your tweet, and are eagerly waiting for it ;).  


Now try use a hashtag. 

"Wow #rstats is awesome!" Now people browsing this hashtag are more likely to see your tweet. 

You'll get the hang of this in no-time.

We'll dissect some tweets later, but you get the idea.

Just a little tip, limit the use of hashtags to 3 or less in a tweet to keep it legible. Using camel case (#ThisIsCamelCase) makes hashtags more readable, and ensures screen readers pronounce the hashtag as separate words.

<Allison Horst's image on cases?>


<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Make sure you capitalize the first letter of each word in hashtags so that screen reader software reads out each word separately. It also makes them <a href="https://twitter.com/hashtag/EasierToRead?src=hash&amp;ref_src=twsrc%5Etfw">#EasierToRead</a>! <a href="https://t.co/ydkRk8eRw0">https://t.co/ydkRk8eRw0</a></p>&mdash; RNIB (@RNIB) <a href="https://twitter.com/RNIB/status/976453467874234369?ref_src=twsrc%5Etfw">March 21, 2018</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> 


